### Create User
POST http://localhost:3000/user/signup
content-type: application/json

{
  "email": "test1@test.com",
  "nickname": "test1",
  "password": "11112222",
  "phone": "01011111111"
}

### Login
POST http://localhost:3000/user/signin
content-type: application/json

{
  "email": "test1@test.com",
  "password": "11112222"
}

### Update User

### Get User
GET http://localhost:3000/user/getUser/test1@test.com