name: run test lolink-front-test

on:
  push:
    paths:
      - lolink/lolink_front*/**

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2

        with:
          node-version: ${{ secrets.NODE_VERSION }}

      - name: Install dependencies
        run: yarn

      - name: Test
        run: yarn test
