# name: run test lolink-chat-ci

# on:
#   push:
#     branches:
#       - main
#     paths:
#       - lolink/lolink-chat

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Install dependencies
#         run: yarn install
