name: Deploy EC2 lolink-chat

on:
  pull_request:
    branches:
      - staging
    paths:
      - lolink_chat*/**
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ secrets.NODE_VERSION }}

      - name: Set env
        run: |
          cd lolink_chat &&
          touch .env &&
          echo "${{ secrets.DEV_CHAT_ENV }}" >> .env

      - name: Install dependencies
        run: yarn

      - name: Build Zip
        run: zip -r lolink-chat.zip lolink_chat

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Connect AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload S3 Server build zip
        run: |
          aws s3 cp --region ap-northeast-2 ./lolink-chat.zip s3://lolink-deploy-bucket

      - name: AWS CodeDeploy EC2
        run: aws deploy create-deployment
          --application-name lolink_dev
          --deployment-config-name CodeDeployDefault.OneAtATime
          --deployment-group-name dev
          --s3-location bucket=lolink-deploy-bucket,bundleType=zip,key=lolink-chat.zip
